services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    hostname: selenoid
    networks:
      - selenoid
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json:ro
    command: >
      -conf /etc/selenoid/browsers.json
      -container-network selenoid
      -limit 10

  selenoid_ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid_ui
    hostname: selenoid_ui
    depends_on:
      - selenoid
    networks:
      - selenoid
    ports:
      - "8080:8083"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  mariadb:
    image: mysql:8.0
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: password
    ports:
      - '3306:3366'
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - selenoid

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - '8082:80'
    depends_on:
      - mariadb
    networks:
      - selenoid

  opencart:
    image: agridyaev/opencart:4.0.2-3-debian-12-r33
    container_name: opencart
    ports:
      - '8081:8080'
    environment:
      OPENCART_DATABASE_HOST: mariadb
      OPENCART_DATABASE_PORT_NUMBER: 3306
      OPENCART_DATABASE_USER: opencart
      OPENCART_DATABASE_NAME: opencart
      OPENCART_USERNAME: admin
      OPENCART_PASSWORD: admin
      ALLOW_EMPTY_PASSWORD: yes
    depends_on:
      - mariadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - selenoid

  tests:
    build:
      context: ..
      dockerfile: Dockerfile
    image: opencart-tests
    container_name: opencart_tests
    working_dir: scr
    depends_on:
      - selenoid_ui
      - opencart
    command: >
      pytest -v test_part3.py
      --url opencart:8080
      --browser chrome
      --browser_version 128.0
      --executor selenoid
    networks:
      - selenoid

volumes:
  mariadb_data:

networks:
  test_network:
    name: selenoid
    external: true
